### PR TITLE
re-submitting pull request

### PR DESCRIPTION
**Pull request by Dedsecproject**

### CODE REVIEW

**Comment by melvyniandrag** [comment]
You have merge conflicts. Your Week8/homework.txt and Week9/id_rsa.pub. I can sort them out in a few days, or if you have time you can make sure your Week 9 and Week 8 directories don't clash with mine. I think that means deleting your homework.txt and id_rsa.pub files.

**Comment by Dedsecproject** [comment]
Wow. I don't have any files in those directories yet. I'll remove the
branch entirely and start over.

**Comment by melvyniandrag** [comment]
I got the new files from this pull request, looks like only Week7 stuff in here. Check out the class repo - if your week 7 stuff looks correct then you can close this request.

**Comment by Dedsecproject** [comment]
That's weird, I push extra credit and week 11

**Comment by melvyniandrag** [comment]
This is the old pull request. Looks like you deleted your copy of the repo that contained these files. I got the new PR you sent with the week10 & extra credit already.

**Comment by Dedsecproject** [comment]
Oh OK Thanks!

**Comment by melvyniandrag** [comment]
Ok I'm going to take the initiative and close this for you.

**Pull request closed without merging**
